// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countByUser = `-- name: CountByUser :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1
`

func (q *Queries) CountByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadByUser = `-- name: CountUnreadByUser :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :exec
INSERT INTO notifications (user_id, type, title, body, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Type    string    `json:"type"`
	Title   *string   `json:"title"`
	Body    *string   `json:"body"`
	Payload []byte    `json:"payload"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Payload,
	)
	return err
}

const listByUser = `-- name: ListByUser :many
SELECT id, user_id, type, title, body, payload, is_read, created_at, read_at
  FROM notifications
 WHERE user_id = $1
 ORDER BY created_at DESC
 LIMIT $2 OFFSET $3
`

type ListByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListByUser(ctx context.Context, arg ListByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Payload,
			&i.IsRead,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :execrows
UPDATE notifications
   SET is_read = true, read_at = now()
 WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOneRead = `-- name: MarkOneRead :execrows
UPDATE notifications
   SET is_read = true, read_at = now()
 WHERE id = $1 AND user_id = $2 AND is_read = false
`

type MarkOneReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkOneRead(ctx context.Context, arg MarkOneReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOneRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
