// SHARED PROTO — copy this file into:
//   backend/user-service/proto/user/v1/user.proto       (Go gRPC server)
//   backend/auth-service/src/main/proto/user/v1/user.proto  (Java gRPC client)
// Keep all 3 copies in sync. When the contract changes, regen both sides.
//
// Why this RPC is sync (not async event): registration is a low-volume,
// strong-consistency flow — user expects a working profile immediately
// after register. Sync gRPC gives that at the cost of coupling auth-service
// to user-service availability. Acceptable trade-off for this flow.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: proto/user/v1/user.proto

package userv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserInternal_CreateProfile_FullMethodName = "/zalord.user.v1.UserInternal/CreateProfile"
)

// UserInternalClient is the client API for UserInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal-only service exposed by user-service on a gRPC port distinct from
// its public REST port. Not routed through Kong — service-to-service traffic
// stays on the docker network.
type UserInternalClient interface {
	// Idempotent: re-calling with the same userId is a no-op (UNIQUE constraint
	// on profiles.user_id). Returns the existing profile if it was already created.
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
}

type userInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInternalClient(cc grpc.ClientConnInterface) UserInternalClient {
	return &userInternalClient{cc}
}

func (c *userInternalClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, UserInternal_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInternalServer is the server API for UserInternal service.
// All implementations must embed UnimplementedUserInternalServer
// for forward compatibility.
//
// Internal-only service exposed by user-service on a gRPC port distinct from
// its public REST port. Not routed through Kong — service-to-service traffic
// stays on the docker network.
type UserInternalServer interface {
	// Idempotent: re-calling with the same userId is a no-op (UNIQUE constraint
	// on profiles.user_id). Returns the existing profile if it was already created.
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	mustEmbedUnimplementedUserInternalServer()
}

// UnimplementedUserInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserInternalServer struct{}

func (UnimplementedUserInternalServer) CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedUserInternalServer) mustEmbedUnimplementedUserInternalServer() {}
func (UnimplementedUserInternalServer) testEmbeddedByValue()                      {}

// UnsafeUserInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserInternalServer will
// result in compilation errors.
type UnsafeUserInternalServer interface {
	mustEmbedUnimplementedUserInternalServer()
}

func RegisterUserInternalServer(s grpc.ServiceRegistrar, srv UserInternalServer) {
	// If the following call panics, it indicates UnimplementedUserInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserInternal_ServiceDesc, srv)
}

func _UserInternal_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInternalServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserInternal_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInternalServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInternal_ServiceDesc is the grpc.ServiceDesc for UserInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zalord.user.v1.UserInternal",
	HandlerType: (*UserInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _UserInternal_CreateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user/v1/user.proto",
}
