apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:YAuFQqZ/hijYBGh2Iehn2W9W0cRmKtYPlcqxOPRLTJXOk8E=,iv:92GcK/mllHRr3FsWF4JRVhj6cnlelS/KkwBmuKx2mA4=,tag:qIfVbMpvfnlQF8RFPVK0ww==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:NUzZLcVt,iv:9plsoNPC2BkjDtvzbj5o7gNFdMrplXm3iixhTdmPwJc=,tag:lw1Nv1DCXnUq2QCWZyMcKA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kysnL38Q,iv:PSwLVwC+ytZOy9h5yIrhK1kuRjwYif3Yldd9QTkeEZc=,tag:4ecifQD8gIjsZ0jW0/u1QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR3c5a3g0VnlwVW1xV29I
            a3JUcCtwR1BhUGlaR1Z0RTVSM0ZVQ0tJZ2hNCkdPM09WQkVPRXRvK3ppdFdOWFN0
            VEdyRGNRVUpiWXZwcU01TnFVYkh0alEKLS0tIFBvV0VPZ3hJTDYrdEFMZnc5V0dq
            RFlLdjRJTUFydjVzdTczcDd0YkxOUEUK8XvNXITlP6dHwvojK2nllQDslEmWdSIW
            68UzOaGsOw29pg/Z9Ypo1mK62xf96UiPB4fX3Lqg8YnEB8XEK6vYOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:zS2Oyg5zYJbI//7MwwxVYs6/Q+7X3NrbxIAfzXWycwptsGIQG30XmF2PRNCWc9DRtEjKtsWiSuDClvJiERt3TOEBc6KDF9MbNf9gkQL9VG7xeo9iRe8VSlW0J5Z7rUMN3aI0e/d1QRg34N01ut974TcqKwa9Hku30JVRHgJe55I=,iv:CM7Km/6GUQHYZOroiiAfMqAxFqU4I/MFO+MX5f5U+P0=,tag:4nIOkHb6jZvvL6qa4n44Ow==,type:str]
    version: 3.13.1
