apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:pUXi1TczMac50vtIyMLBc1d8B1Zgs+5VuXTRo8tTKMxKQ5k=,iv:rpcwq5EVQlTcoJm8e1yMdYomMmuKfkJuxbmyNKixHtg=,tag:Ixf/YFF3zTxbOcXIqF8vCA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3eG0dEMW,iv:nDGZFMOySUwPxnAbuGNGu8hnLnJuwYNMiJXkLQDMZ0g=,tag:YxROO/3/dFDlEOrxJv6MhA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QvlGxO9c,iv:N1MJs9Xey8k3NPNkPXR1r1s4vz+RGPvwAU346Vju+SU=,tag:/jp+0HFgxR3vKCudqzUEGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MitjVVl4T2lJQjdYTERM
            T1RSYWJzcmEwSVdSY0VSL2JYMjVZWk9YbXdZCjJiTGpDWXl6d0w3OE5XeFhvc3JS
            bCtrR01pNVkxbFJsZkQrcXluUmdKS2MKLS0tIGNITXQ3RzUwVU9BbE81K2EyR1Bx
            K20wcGFIcmJVTnk1SjJ1ZExSQVZ6VTgKpNpQkWAMrMfujvg7BObwVLQvND/+eeB8
            8j64GsNbSgQaV8GBK7Ki6k07j+TsoO977wNGBIaMqzEeosYFL1FxWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:31Z"
    mac: ENC[AES256_GCM,data:cK6NGXCCT6qObgfJiuWsQd6Jn16X67LWtvDi8JAPkFuMeE4Bqfkte8yVEuO2iQqbL1hTUjbYpYlUkNOnyXN9Mu6RJwR2UdxAOFoP8MK1/xG7lsI0M2g9UWcG6du3Sf4jZz4IbFxz45zlr8jf4a6ldLO2VCu2TDrsDxhMKMD31fA=,iv:C2xKlCpeMCwIMTxEwF3Yx9FKVnBQp1tPFp1XNZHdQtE=,tag:xtCdaotggigehej+Z8k8+A==,type:str]
    version: 3.13.1
