apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:FkRTlYGf,iv:8ZgMbjpRwR85kagwJutuM5HH59TAqXh+s98LFeLPX8U=,tag:eVklM9Fj4BJH6tKbMRWflg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0c4Hj/LG,iv:Bb1CVaB/AVyuT27hwZQf1Gi4658nfH7Xg89FFUO3fQg=,tag:VDajzglFJjoWZ9KS/IFbFw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:dLrcY2m68KSv8CRRMeuDiLgzTPc0oWPPwLKqcYQ6jCDLx4M=,iv:SYYOMV5cejDXaOx8f8LjKXEm/0474BKrdQHwnfr+vmE=,tag:duqzDCVgxH/nBctgxTtmaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdE9YMXErUUtzQjVzeTg3
            YVg4YTAvWmZ4blBXZGkzTTFpQWVxemNlK2lrCmowTi9tcHhwYm8xYVd5WHlPQlhw
            QlBDNEd6dmVkVVRra0NxRFluS1pWQ1EKLS0tIGRzWlptVHRUVUM1RkRDZ0kvdnAy
            bE1ISDdEb1B4UnVXYnpsK1I0akhtOGMKi2oJk1sY3pa7Jk+SQw9VYE3nMhOPuHhg
            TVffqY4e0+gWuJRMzK9XIWYOvzBKm0j6YR2swefFlhgJyTDCWXjNNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:43Z"
    mac: ENC[AES256_GCM,data:wbwW4C4ueakehO1c0BDOmS7yiblHy1Y5cVWUzwsdL7Zjqc7S9dK5WFICgRKGUa6dE6dyHeC4zsrTMCoNvHL771qr/UqzjQA1/sX55tTiAV8avSdnlR0aTRKilXv/lAkde1+e9KmW5/guUbKom0EzEu9VtlFyChuOewBNk/qoSDI=,iv:2rGrpCDssQx9eLoi+oLgl46/HP5c/Q/fTd2XGsLLY8k=,tag:BuFDjLgwcLxqwMF5cr96FQ==,type:str]
    version: 3.13.1
