apiVersion: v1
kind: Secret
metadata:
    name: chat-service-secret
    namespace: zalord-staging
type: Opaque
stringData: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3LzF0aGYzRWYwZDF0c2hr
            TEZyb3piQ1dUQlQ0K3lTeHV0ZUprN2M2eHd3CkRFMGY0dDh4L3dPSDIyak84S0Ey
            MXUwRnJwQVF5bGJmZFhXOGozU1pZa0UKLS0tIDJoT3BBdDkybUFQR3RpQzdmZ29m
            QStlUWhCZ3hzb1JxSTNVZkVHKzFDRjQKrA/SzfQwYaR2FcFX12UbGZWtvBJWH7t0
            cctz3IW3up9BG5tpj2IVGOUiuXSwgHlSTeI0fWDW1EitTU4er9nVXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:38:31Z"
    mac: ENC[AES256_GCM,data:r4Rip6GWiUObVzOaX56ul/bqjoU4Vb5Z1dCYPK5Utw8Igvr1CyZFza+jCXQkRxmWCBCMGnTc7U8bTLgDwTkzoGAK0RyyDNcFvuu7nf+EmFdDC8SOfkMc7Up3KF3KEvWNKDfAe0VsLr9/Y3pquZhU9/Y48DRxQ+sBUxX30xcpYuA=,iv:zEpJVwjnFFihvw/XrCsMK8G50SJUHMvLsXPGExdFhvs=,tag:gVxl32t+QtijG2BwiYIVBA==,type:str]
    version: 3.13.1
