apiVersion: v1
kind: Secret
metadata:
    name: chat-service-secret
    namespace: zalord-staging
type: Opaque
stringData: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MHFhOTh2Uk13NkhkQ3lv
            blBGWEpJL3NDbGNlak43SnpsQittQ3VLZWc0CnZBQ29EdXBJbHlDSndtRThVNThV
            RnNFVkY3eE1rUURqWjFPcUsxd3NoTVUKLS0tIGQxVWZVYzIyaGdWNEVKWi8zZjBj
            Ykx0ZlBOYWdrU0pHTW8wYnE2OUZtYWcK4j/e0Do8PiRkjLyinJZKyTLjVwQNdHs2
            AdiiHmATqfXyo+4qXmc7e9gkvqVacB18GLBuMjPM2cYnPWseqlTPxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:43Z"
    mac: ENC[AES256_GCM,data:334aqH80eHtMi7ABEY68dccBqcp2GZUUdDRyhO2lQAVgdNEm6iGcsGFVGM8Szn2dzt1CAc/mST6WA3kTKqPFvUQ97AdhklscI24wqRV0tRpfbj5XCUidhvpBsbV0ZwXdSLp4587pGp49ZMPz3a/cGvBN899+B26nNS2Wdb8cH/c=,iv:wfdBPaU9/dW9yz+XhiwHpW/1E0dminUhaLTzOmuE5x4=,tag:VtzSEtYQz7Xi5ZjA6rc1xQ==,type:str]
    version: 3.13.1
