apiVersion: v1
kind: Secret
metadata:
    name: group-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:sC5wDQ9B,iv:ly3dkGUhQwJjWj2mRH5uIvMWUr1tyieKDyaypMj2zaI=,tag:hmlio1CKYyNIoCqYQHZljg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:V6xyeela,iv:MVzu8F1l6UxbL+c1hnmLkZr6dzUFfj8aMujkgtWKPvk=,tag:Q7T6ZqVOz1WkuQGck9TAyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VTBoRWFMdDdBdHBZSEFM
            VXlheFhDSVlsU1dGQUQzU3NKcXJ6TVhJamtNCjdraDlXWEpDQnQwT0ZwK0N5bG5C
            M1ZYOU44OGhaRFBoK1pXRmkvdnlrT0EKLS0tIGFRRGU2U0IrR1JIVEg0ZEJaaVhP
            SU9TRFBoOUk0M21qRWRtRWJCeElka2cKSsKAl68jioAyNu0s1NI/Gledga9PHtzw
            L0pLQ5gICkBSlLdGFThEpKLPtlAk6U2BRoroyo76JMgF8mgfsHiSNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:32Z"
    mac: ENC[AES256_GCM,data:4H3yrhWKDOdXvzhwxnnxkGcj4lVu/keqe/badpSpejw8VBOgJq84cE8i7sUV4nVSvRmth3McsftvV5b+XQP1ykhzLsFod16iq9Vml5B+n/x5H83y63w4AH+XIdD4NgvuL3kS5MSfHWESNf/uFM07j0uLWmA5Ow82lQa9ArLWPU0=,iv:N+pcSbuA+TOOkoMvF2HL7uR69LCRmyAhzARMw+o0a/E=,tag:W27cUHjNL3B/VGeH5RjGGQ==,type:str]
    version: 3.13.1
