apiVersion: v1
kind: Secret
metadata:
    name: group-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:QNSFzEmk,iv:3br4JGAt4n+NpCVtnm948EJqWettjS6LgehyH2iBMuc=,tag:Eb6/LZAqvHWQcrAH524zsA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gKtGG0E3,iv:aHpbLktby9HjBHKioczcBOCoUq36BRaS/38i3+eyt/o=,tag:8ZGsNf0+tfSeUpzB9Zy2Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVo3QkkwdHVVdGtsQzJH
            UWw2UVZyS0NIK3hJUHE4L0Y5YW5WV0pVQkMwCnowSDI3UzJhZk5Kc0tuNkRja1Qy
            Y281NTYzaWF5dEtYbmZ0RVFsM0N6eTAKLS0tIEtEWGtVYktkVDA1OUwzSHM5WWZR
            VnFvY3FJWjdlcUtpazlJamIrUXNhcW8KD2KcwPy4/3L2x0uJ07yAF5fQt/7gQ6fz
            EERwulkv3ttCkY1UKsaWljhl+FHEh/mdyml+bfLcqWoZPZNCZuH9vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:REN2KlWGXw3bVVfh2ZaCI0t6hGC4vNSheh0zbmkzO0IcESb6PPYXe0Gkt5pfAP/rPaDN/G7buzskUj6eh3L4q/qdzG8QAt7oqzA6tHPUVAcrGsO3cZQb7/A5W3xPd8EmplygWyVdCsT7Wtz7J+RyHb2FcRpEp6OqkBpybKB4WQE=,iv:ZSDw6kP+DCQVzTR69jqar1bWj4ml5lpRruiIGco+IrQ=,tag:bBsmO42DocjFBE6EcZNzSQ==,type:str]
    version: 3.13.1
