apiVersion: v1
kind: Secret
metadata:
    name: media-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:dGvIIepA,iv:ZoVQeefStLm6RkXkC76+o+A5/jsUvA0xS+CScEgipjo=,tag:swRzksM5Q31TdIXSq9Zytg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JwTVpC2i,iv:CDS6xbKHrm0FESr1efglJnSyzU6lUAt0d242+FRDcvo=,tag:g11JBVBAd1kmPkk9a9GCvA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Uh1uNbA=,iv:O2jKTsBgzWtcq84vPmkHpOvsQBIh2wdXHlV+vsFHfIs=,tag:GuwVMs046pynK4YDb3xA2w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:qZQwuBAKWUEjW/Cs,iv:E0n7MOL2qqA4rOgadMa/dviUNiCc6ea9JaHh4tHwwZc=,tag:ubeXQH6dSa4enrNiyC1ihw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlpaUHNMc0hzUk1WMTd2
            QURWWW1zWTB6YVFTVEdLRHhZVWJLU1p1RkZZCjh2TGVTY0JDQjRFbWdkTzdFcFVp
            dmwyYUdFY1hhK3pjVDlTRzZpWkFsMTgKLS0tIHZ1Ny9YV21lejZzTEtsdUNsUXJZ
            ZHdTKyt1R3BkOEV5Qi9KQlpUTnloRWcKsFRAMqVI2od10TZUHz8qtlVe1TDobtja
            f33heFnd+FwH2gZCYSQsDiHsmqolGjmxdEiE9OfBegwuz4JoyNtCZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:UQ6iV92cNnReX+62H0+ov1VywW9cm8kUR4qiKo8BpDemc8maKRxm2oaKSdC2FBGiNi7HWvtyz8Ok3O0t/EFxy12ITuePiu8iB1722XqEmDDxxVBi3OcEOpnXYrncKfMkKHmni9iwUOJOkC99eCTebcF0/6XkwbKvUxdg0nsSj78=,iv:/rNVKMUjkZhorbEVxi0+6LJCioXxIb2dmee1jaDtnLY=,tag:m2j1UVk8ywWi87wTGB6VCA==,type:str]
    version: 3.13.1
