apiVersion: v1
kind: Secret
metadata:
    name: media-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:eu9Svi8H,iv:xyYMQfy1GQkwAUF+3vowFU4XhjzU49u609NJfMSzjc4=,tag:GQosOjBDr2ij/GyOVwtjsg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wFx1NDH2,iv:GGxqgP5fE7UPrwZpUjAdkqw8MEEjaFlOYvxOIudF8Zg=,tag:KhI7Z6qCAV0IFhY4Rj4QfQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:MwKitqA=,iv:0epbi0EJz/tgOBl96fKQvNWHa0tCy3HU/tCtUfHoxGs=,tag:KB3nGpMe9knz699ADqPQ8w==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:rhdmsnUYo3C6aq7n,iv:l2LGUzpmGSi6TUUKguHRUZzItqc5WupdjSAVOHai5zw=,tag:5iUasP+a3BvdANam9biGEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOME1Cd29CcmxkekhoM1V6
            SzhGUFhzOGlXc3lHcmtCcjU4NWJpTzBiVm04CnRMd3hQdG55M0hYeHd4REtBV0Y3
            T1FuZU84aFlHVUlGdWtKK20yYjlQa2MKLS0tIDB6S2pHZWN4RjY0WStKT0F0TWcr
            Q0hDT2VOaS9yQVp1MlZER0RzdC9aYmMK0UY0XJhRj22WBdyz/acDTVWxxVRAcF0a
            CN2mYnwVu6uE3FgXm3Tf3K/84xFuhBXBSxSi8r8P1vaRP0F3Ia3CDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:32Z"
    mac: ENC[AES256_GCM,data:4hMIoehiz4wYmbOWEaKbhbhTkQjD8tu7cKVTfVbBtO7LVubYOyEfiDuXeXfYaEDWIP+al1Mn9Kj6+bvRwsfU6kqv6EwjxsOKxn5TrB9/kdT/npILL9GriW9hlY9HhE3M5jw91A/Lwoy40ZTCXisKXaECQFGBkTVE+jrsPNKLWEQ=,iv:9fdbWZ3QmSgeV60+tZQDZwRvyD6iXdWxCvACMBh/o8M=,tag:4CRQY0Gm6RZgAaDGqbe4fA==,type:str]
    version: 3.13.1
