# Development placeholder values. Replace before using outside dev.
apiVersion: v1
kind: Secret
metadata:
    name: media-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:XieI0Cdx,iv:gb+gwxrE+5IcVI/Fn5LbahvU0ojmyMc4R9eDSzghim4=,tag:P2qEr3XtznzltLuDdO+UWg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QhEnYMVt,iv:APbJchgd+3Tn5PS7WfUDknD0sz+PLLal6hvVHe+p/N0=,tag:chvkCjoZd/nsLV4RDbr2yA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:cMgpdJoE25xsUQ==,iv:eTsLxSKoG+U2AHt4RIiQjfAd+b8Lm/V7topcWtQA3GY=,tag:FkC1hjQzBI/FomRgrr3qRg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:vPUXHOr2gfoGAKsUGGP6,iv:VPLesLX1eml8se+Ab1ArhkEuWiGR4ddBG3HFrZieUJk=,tag:M8K53iGs4Qevqj6Ub3MhUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaWltOWw4UnBpWmtYQUpU
            N1ZGRTJPRlJibUk0a1VWMFFaUklISldBNVdRCndKcjMxVyt4ckJ6MXZOYWdaQmdO
            d3A5S2Y0SVBUR3VCN0c1bS9uem9Ba1EKLS0tIGovZ0xMRXhaQ0I2Tk9RS2JEd1p2
            WnZSWUdKZ0FVaHljWDFTQ2QzNlJPT1EKM+d7rWZ1FULTR+qI0YcxJ61HdF7uhJpX
            Sakyi2F0BMXX8TZQ8Lf/hJwZIBnofAilNGCbHoWFN91DycPs3gw7CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:44Z"
    mac: ENC[AES256_GCM,data:MFagQTVpcJ68ip5zKOmTpFPBEpKTuonex/QqIQkLkP5fo1qKY7+lEBbrRoZ2aODqB2iq7bXbOfm2crUFhBZ+jk9hnyCmP/mwtY2s2hgQMxKFgqayB6H3zI7NHXh5TY9eJCRBy3PO21uSv3ptprgl13+UC/V0EKfk5YzToH4iMMI=,iv:TsfekzkV3SHIneDvzZwkVjTklfce+KTEzlttTLRVIaU=,tag:f7yvi8t+LysQNJ0BnMRHKw==,type:str]
    version: 3.13.1
