apiVersion: v1
kind: Secret
metadata:
    name: message-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Sdsmwpai,iv:mxjIcr61iezuB4FPrTkSjr2geaiHrn9OVFD0FiZs1V0=,tag:HMMj8ifkmV1SdHbmMQXHMA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CBWxe7WC,iv:9SscRS6AG/yKYAZX2xl5ZQYI9wo6R0G8I7XvQKpJ6Q4=,tag:z2ohKDSx5dOV6UD9hm5yMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U0JJTzhxY3FKWldYUi94
            d09mOVVmTnV1Si9HTjFxRURvTjNKTVU3L0hzClNTTFpKVG9OVGlZbWd3d29NMXNt
            RHNsU1lCOVJPT1hrQnNFKzNKT3ZWbjAKLS0tIHNmNmNNR25mT2FHWWg0cVF1QWE5
            MHFMd2h3TlRUUVBqZExIUVVTVjFwc3cKzHKWXe1hMujTU8XHoL6s2IchFo4VV+bK
            FQU1FIQT9H9l58ERQph9Sg+YQA/mNK8WCmL2mXZxbkkajtIVKUzADQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:Ficy0Tcizd8EukTBUSsMy2eh3DVVJ+zxTFHfhN1JAb/2qloVkD7ufhVjmO7mbrsr7pBDCX/dGFrWSlOe+f4Tp2kAjd8TUSwburG481ZCYaTDr83aPZKmBZE9Lfr+TaTYVL8x4hAjsFX0gXfTQxDtafrr+mIe8aBWTwfHAOWsVfA=,iv:JOBj/kRETmMS58wMEt6mrnWHLfXNjiPpg6tKcfXc2nQ=,tag:5kliKoFxuyEgmiJLqh/shg==,type:str]
    version: 3.13.1
