apiVersion: v1
kind: Secret
metadata:
    name: message-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:nn9QW3h3,iv:N5WBbf24LulGE8J13jZLohFLAH4Tt/1zXJRJvHS+Tlk=,tag:eDYIwODZ2h9Rt6FtsUPLRg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:h52Ern63,iv:DLr0hSknwwjZaz/hMPLmn8U22VHekVFUI9HkqHhWjDU=,tag:LLa5qY8xV9G/CT/dFl144g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmlOSWZaNEJUYlhvcUly
            U29KL2xtRWRRVk0zTFpsVlUrZzN0OWFmZGlzCnNqZHJhK0Rod2d0WVlNMXRCc0NM
            aitBRld3RnhDYUJQcHgwSGo0SjdPNlUKLS0tIDRtaFhMN0dPL05weDhBdm9LM1R0
            U2NGU3RraGpnMzQxVE9SeFJoY2h6OWcKUPmWNUfFnPyL9QHQvN0iKHnb3K3IVr/4
            M1lEKrv3LCI7wfLo660IK01w62ni2LNzoQHpX1wNvpxzg/3Ft9x+mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:45Z"
    mac: ENC[AES256_GCM,data:UZWgTG8A6RNGfbw2g7ZJesiNLCeUQm8z5xu4iSsMR8p0HaE0y9LD2ip9KKLE2+49zE44BgxTePt0KRfgyvXxTfHayl5SaeNnbu35/+UcEkoXQWU3eDXRn5pCdUrrz2p62rxBn+OZiNpFlCpeXnAPC8TntulsCtE9zW9f4vWfx4k=,iv:gH6q3Hbnp3sGoS74sqSOypJ2cDtPQunHfTCEs3aUOEI=,tag:7VjQ5NZ/j83yDIt3/Oa3iA==,type:str]
    version: 3.13.1
