apiVersion: v1
kind: Secret
metadata:
    name: message-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KN+QWbAF,iv:NWcpVfI9JNvcZZrYCwXBHiJzekp6Q8Mdt3/39dkXZy4=,tag:Z+RS7PGibb7DhY254v66GQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LktBHnAV,iv:kCivu/u4qfFMO12kSx5QmWzD0Usi9FIFgLM5/sgHohE=,tag:jaC2TGX0dLF1XN17txfWcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3UvTDl0NkNXdVVIeHlw
            c0RTUi80Wm84cGJuZFJiSFBlR1lwRVlua0ZjCjhKbUdXRlFnbGlPQW02K1hCdnlv
            WGUyOEFTK01kdXB2VzF3NEl5NHFiNW8KLS0tIEdOc1dBU3J4NEhUN0IrTTRHMXk2
            S3B1ZVlWRXFwUXRpclRXMllBZkdITk0KMUmQdcNF26/6LlxdqhNzVF7lYMrYnLNC
            Kh3bfrSKOazMOAojh1QhAD5p/GRV/+G+JMP4hb1wevlJvuKVEwMHGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:32Z"
    mac: ENC[AES256_GCM,data:O2RItv12J49Y5g6tln26EGX6s+HoTk7V8CuvEFizqII1yTOJDrcZ7p7qnvOH95azQqvNAl+T6cqRRx0TmjZpC1PK4QDJoFKZD2r6dGlCVQBXlQS1bzwOgPdl52xfZ4rqMpbjYcVeV9SPRek+fsNdT1GrVGfnc/uRdRNOOFU5N/k=,iv:3pjBbbnSGbtjm7v6uMhD2Tw8Dcc9O99P17uikkxkVDQ=,tag:hHMY2YBnchPlBwOC7rvKkQ==,type:str]
    version: 3.13.1
