apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:rGY/Bilw,iv:/SwjFm1qAGdLWGZYR9UX9hrjIJuj8BfGSTDlcLbNdv4=,tag:1Lbc+5af1HER3alHdzA2ig==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AtR2SFJg,iv:66eJj2tnc7KdKp3XH6yY9Rg8JQtQSip1X4uK9ZMHWB4=,tag:/wulVxRJGsWHzuGgWJnTHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWmRnZnpvdTU2OGR2eEdx
            ZVpZZmJPNDRWSHpnVEMyMjByWHNQbzg2UkVJCnc0ZXJTcXNYa0JhdzB1VUpqRWgv
            S0ZPbWk4cUpKWDloSnFWR01iaE5TdXMKLS0tIDQycE91VmU3RS9EZXlEdjc2WHJD
            T3RIUzJRNTNVRzdxNnRJRHVtZW5zNEEKH2ODBDHnZ24wE5y8WqXJ38rH1PEkDVCI
            r4uqRL9FkNZ4d8jzi+yNHo2+PlWK0JYgJOnWGf6RMzoxA4iizhRV1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:32Z"
    mac: ENC[AES256_GCM,data:C1k+6wHA7gy+tTkRP3BkDWVUs4X2lk/QE/DhSv1WqHIyPbqnPqtxGe7ehnS+kWR79tweH70S62C6XCnfaEp8WZgUjbECmD8nHN+IQYeCKp5wlgCZAyIGV5YtlDhFx8zu0g23tivMZNSR8k/Jld1H8nl8YjSgeVSUUhgUqv+Q9Nc=,iv:/yz6uS6F3EQgolFhPHVzaptOkGXWbbZtonSXjxAtc5k=,tag:RK8dKsEwh4ZvY4ixA3pxhQ==,type:str]
    version: 3.13.1
