apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:vxMA+Ct/,iv:lPSL8KxhFskaT/vDdijB5vapAiqNs0lb3yc+2+Wvnyw=,tag:/0Ti6E5rr23N6mlvTYyZ6g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CB051HW0,iv:W+zNImv0Qaw8qTXBiwUkrPrcCFCk2UikvmpP6l1GUTY=,tag:Yfh3mGpznd73G5QCn2NY/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYW1hejMvUldHUWFwaENJ
            M29ucTIyZFl5ZjMvVjZTa08rWnJnU2hTWGhVCkprdEcxaXRITEtySzh4VXVFRWY2
            cDRvTjgxbkZ3SVRTdW1vM1N5R2xCWE0KLS0tIEdnWktWaFFmK0tIWUtveUFOd1Vj
            angwQmJVYmxrNlR5ckc1ZGN2bXN0Q2sKQrA7E5chYi7ikp8Dt4n/bJEq4tqIiZpK
            63gvprQ/HS44YOgKpvzruVR7xyY9KOnJsB30bWO7xsmxAFHq8xwQ/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:45Z"
    mac: ENC[AES256_GCM,data:KvSOZRt7eAZx4GzBHpxOShoNBUcibR0gvmot4jYHkyfXOU1JhPoXBDrMCiZUmyiOKLUkpyahaD9/+//R+S1/hdmfOi9zM3UtX5lvs7fnGcwzRmB1Md1A2MJ2ANYM6DukFagASlZs7d7+mx8/OgFaDmZ6ODMTa/0m3cNdn4uiv7s=,iv:djF05jY/JKgvi73soWOy6vBZM6C932XyQj0mq0k2Ims=,tag:PRseG0kYGdPit7T0hF23uA==,type:str]
    version: 3.13.1
