apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Vhbo3hVI,iv:61pBV+TesZSaO3HynrRU0BdJ4mk6sZruO1QCyTfhILY=,tag:fo8+R7vrzFdF3FmbWWOUxQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Cswz4+MJ,iv:Yse6Qt7ni4DpcCADQh0uWoLtIEzgljZWwLwKF3njIrs=,tag:gu3xTQXSbx52itsR8OqwSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ3ppOG9XdVQvVEQ2S1kr
            aTBva25YKzRkaE9YOUdHOWlWVXRiRGc3U25ZClJMaWVuNUhySVdlS3JqY0tVRldm
            K3h0Zkpxa1k1UkVJdEFVNzhHVjBrNjAKLS0tIHVHMmlzZGJhRHlId0xNSTRoL3pa
            cGdsR1NVODJoOTZDVG10NUw4Qm9FT3cK4Uzw3erq+MvndbBnOqPZWywLJKGzoDYA
            21zRhUC2PYoLqAZllO9NcaAnzsO9UtRbgUTpVPSTiMKYTFJCMERTdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:M8V5rYSYo2evwOYx02eSn3KpTmTBmCtFe7MrozUVQtGBErDuvNCmJaF6S9Zs2Bw759YqF5OaoBakA9I6P2MlUSl7EXqaWsmu07q8ZSEhr4iHOzzwtr+wzlXUURgUbZ9N1mt/nRKjF80+BGYAJFn9tJ05Xj4rCkSmpu9OTAVNs1A=,iv:kuEMGTG9MnaFQwJvI8qjXEfeCvM/Q+e8IO/FNqEoUs8=,tag:0JNcronnLBsZhzm62kYESQ==,type:str]
    version: 3.13.1
