apiVersion: v1
kind: Secret
metadata:
    name: shared-secret
    namespace: zalord-staging
type: Opaque
stringData:
    RABBITMQ_USER: ENC[AES256_GCM,data:lN8tZDQ=,iv:slrXJ9UN4sBfZNurZDjT/hSkQqvVbpIprAaLuoaGtO4=,tag:oNlyyidv6QlwBwm444jJxg==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:euiJdMw=,iv:iKFvOntKpxvQwPDcuG8phDZ6OnG15LRejWky76x5Y7o=,tag:9y5mxLmdZdV/c/Dczzvfjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdzJCay9VdnB1K3c4U0tV
            R296WXJ6UTdORlFXQkxiS3pFSVUzTXR4Um44CmRnTWhkTHh2TzdHY2dMV1FZSnV1
            RXhYSzA2WHd3UnNLS0lVYzYzMlpTREUKLS0tIGFzNGlNa0hmckFvWFBCdXFIYys2
            U21ZUy9qN2dDanpMQ2pDMmdyN21nTUUKZGxcXljC0ykt2CAsQH8KBBIansPXIAYU
            5ZVI/LFJDBk+W1A9qs28Yeccdh7jJw7fyWUZnlE1Z3Cf0MBX0aC7DA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:31Z"
    mac: ENC[AES256_GCM,data:823deVjPuxVKhA36OK8l/Om7rxJQacFCWTEdK35fiStL+5Xo5sYFgyWFg5+Ed5r0yLz+h3W0ccAKww8AYmfjILUoXUP5z6Opr41nMy/CpR967jiho8mDcxhE7Mr9apNwkVjt17jt3tT/u/zggCpBHatNwxfo4BTifho6Ux/s3OA=,iv:VW1vndG4Mcz5PdItYJC2Pm5urAWSV0IIRZ9PJmZcNO8=,tag:4ixzGgKhLdiQg+IPNfOEvg==,type:str]
    version: 3.13.1
