apiVersion: v1
kind: Secret
metadata:
    name: shared-secret
    namespace: zalord-staging
type: Opaque
stringData:
    RABBITMQ_USER: ENC[AES256_GCM,data:ZV3IPhA=,iv:6e+Fi9omFVPSPNo60OPxiGF1A0uoVmyCjQp3ZKW98t0=,tag:/TVFA+GRGNZ66jn1ovUDWA==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:rr6wyk4=,iv:4xa0ekgK2FytZhu9mzp1/MlM0SkX7CVaFB+6xhcjV98=,tag:1X/FV3VKNLsG8ZWUJiU4jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdUxFUk5HbHB2TVlzcWxS
            Wk9POS94ODBSUit6d3JiZFlwRmptaUt6eW1vCmhTcDlrSXNiWmVvTFlvRXlZMDdJ
            MGhQQWpua3RFNWFFY2E5WEJiTUVxQVkKLS0tIHAvQVpXbzVuY0grWmlJMmQ2NlNM
            NlcwVnFPVWVkWDFFSHBIZ0xTeWhjd3MKtwtSbjUTgKa86m1UIG7qdK/jP9AKELG1
            vm+giKCGo60135MKdArWZJmHdQ2JXypd9DeiLsAX6RSWpdh+d3NyQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:46Z"
    mac: ENC[AES256_GCM,data:xEjswSi7vgBWGXMt2SgMCyMlOOlUV7bCsoJM63qelRMz7QV2T51z+vBF75YPDYYZk4wp9qBO6dWeu8BZHLc7oKPdSOb3cwoTPZ209QPPy5PSvMVTxhrohhJX8VW5czj84oNqQyy4AkCvc4ExRl7BiGcVZZ4R82UR0ZgD7//KvEo=,iv:j7O7f41Sbt7b0gn6/Xg5xnbzVC+0AUKvQ6fzEehEruY=,tag:Z8E20fcuGigVOcwhgf/s5A==,type:str]
    version: 3.13.1
