apiVersion: v1
kind: Secret
metadata:
    name: shared-secret
    namespace: zalord-staging
type: Opaque
stringData:
    RABBITMQ_USER: ENC[AES256_GCM,data:aBKasZw=,iv:Hng0WJsi/O8vbZCUO3aW2NPu355VXY9F/1d2xE9P24k=,tag:AX64GjJPmIxrHyJAeZBYMg==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:g4pOxvk=,iv:BDopys4SzjVmTvkYafY4vvFvOdIBSGjfMKlCgKG3rns=,tag:VRoFvvqvdb2c2a6cTlA6og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R244YkE1eWN3cE84NDV3
            bk5OQkg3QTU2T1lmZEtSZE1VbjZ6RWNGODFBCjc2cjk1eEpYUENBVDVOV0RicDBI
            d085NGg4VHRjNHg3OVdUdDZmaFBEcjAKLS0tIGtoQmc1OUZ5SjlLOUNnYm9wczZT
            Q2pFVHJQcWs3RGdXSE50VlQ0ZGFLcUkK577Xj12d2FHQeJUjwjSMqKfRh5/T0prz
            MwHVaRaR3Nl1OUT4QXXBtSX2tw0yJgloiVZ4PEuiOu8FwlFleprp4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:q27BK+GoXqQCEQzkhnpuVioWEPEAoIZKBO1GSxgv2MryjFwpZe+gJ+bAvMDBUB2LQxMfh9lSHYiCrhAJICikYKCfL49UnuuzGuoOEv+EvEvNyPeR7BMwtfMursqxUUmKfJARX/0Gi9DHMK0kNE17XrpDaeUdpT6ndIDTCnRX/Bc=,iv:F8VY9WCX3ufooljkYuZb0/dsDiaN1J0H3JMM4JSJSqM=,tag:i6azRc8/sx0/iZvmCdoopg==,type:str]
    version: 3.13.1
