apiVersion: v1
data:
  EVENT_BUS: rabbitmq
  JWT_EXPIRY_MINUTES: "15"
  JWT_ISSUER: zalord
  KAFKA_BOOTSTRAP: kafka:9092
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  name: shared-config
  namespace: zalord-staging
