apiVersion: v1
kind: Secret
metadata:
    name: user-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:mmAgAXlK,iv:j3FNcmB5Xu35NbfCZGejcccFb/9bIJoDiOV/w59wFjQ=,tag:CDcDvRqB8HNXgmk7mRTtFg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ATZOjoHP,iv:iSKdfdh7Ub9fNsKjRxWSN3N6AuQsegC1bncb1544aYA=,tag:9TdqmNWx8bNxUCv+BdLbcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcTl6UVFVK1BNY3EzVHYw
            MVdrSmtVUkdySk5XQkxXVEZ0QWZhNEF1dmxNCnFZWkU5bWN0LzNlZHZ2YkljT01h
            VFNXV1dtUWMwbUd5dHdsMU1LVkpFMWsKLS0tIFF4bXFnNkRTZkJrb0JKcUR4alBN
            cHJSenVvaklyckFvSU9UL2JZTHNFT1EK9/rJ5XKgrp+5I3RnUhDk/UqCRM0OAiEp
            n19Ha5ghsZkji3rS6SnK04kdoGDPTD5wQGeY71MsVEQQX351E3nX5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6jg3u538kktaazrwkh0spqlncydp7c7y9eepxxg9upxn254geysk9q0ka
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:30:31Z"
    mac: ENC[AES256_GCM,data:iCHiZ16DMaftyFa9sphKUn6kcemSDlIoP8U1mGxOwpPuhYSCC0EDKE0ErasbifZHmv+qTIVI0LEodfTkL9wR5fn8zKyAJBqaXNOE9O7HtaNF1bFMvzG89RHaDgT0eSwfgHZLTLUVrC/Vty6BagjHag9dBqj/piGCFv/SqKsH4Nw=,iv:9dUsbwURcPrYR4MVVgcyexb4nSbeiNhau/6IqcO1Spk=,tag:xwYHkejpUbLWGBQ81CDFNQ==,type:str]
    version: 3.13.1
