apiVersion: v1
kind: Secret
metadata:
    name: user-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:w/XoOgK5,iv:Fp96TjE2vtsIOPmN1iq692AEzuFkdDTguWI74IEAJNQ=,tag:H4qggi/JMIMw3J3DcB0XNA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:ooT/2hw5,iv:QEGMES87KA4qsE/M4wA9QswMopuqh664CMu0R5nz/5U=,tag:mDqaTUmqPFEGEiI1XjTeBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOTRKNGdyQ2tiMTYyN3Rh
            ZHAzQzI2TzhiWGs0VnZsNlUyRXhMRmFFa2drClpiSTJZMUdVSmNVbGRMMWc4NDZN
            Rk4ybDV2VjRXVFA4azBLODFXbFRndmcKLS0tIGZkdHE4S3hVS2gwNFpjQTAxbitY
            M1NFUWVDWEdZYkhDeXFhSW1USStxdGsKnHZdda/FLU5hCNttc01r7BHJCUWRudEt
            uzbAgYY+ZS/mFIGRzq6IRXHctQSlRYzsqPEj0Sf3OaWpw+CBWgJNSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fz93gkdk5ytwghkmvxhr7vulgx6haqnwng9l30ka2e5m79r2cvxsrjnyhs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T12:33:46Z"
    mac: ENC[AES256_GCM,data:p5wY3OJIHtb+RtcOwFuC4iXln+VPuiGfCRB7ye+/hhe5tjTXY4R1q9fUS6acxAM8LzDd1pIfGKtsNeA4sMo/5FELnMawtgCd+liWgOs0UKXRfua6JnQZJGlcpXKKmyoEU5IMztPyolH+5PYjYQnjHvTRfQR9wik9TY1+s634shc=,iv:2ZKWn5g7+QEYkvysPq8TiklDFfzkqI1Y7+8IREyCw/U=,tag:VRIdFyFNbdJAMuKT+VyZrg==,type:str]
    version: 3.13.1
