apiVersion: v1
kind: Secret
metadata:
    name: user-service-secret
    namespace: zalord-staging
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:RkTkZeJ+,iv:UgxlRDPkmsIho3biIjaa+hetXwar0GRtdOxEMkaX+Bg=,tag:lPvvL789c+aCzlbPAjghlQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WAJQLriB,iv:zl6ngrBkR/FFiQ9IF36qeLops7yBgMQYY1dn3KUVxIE=,tag:+vzh0uKT8Jj5F7Th90DUGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K2E5dkYxVTA1QXZMWVR1
            djFJV2VLRTVqS2tNeXY1cjJ6MU1QaHh2R0VvCllRaFhlaStkell2eHRGU1VyRkh4
            eHRPUENBTXpkVHJmWlg0U0tvTTAvSVkKLS0tIGYrTkVwV0NNNXZCTUFTR3d1bXZp
            ckl2MHhaSDBGb0czNUhJV1dmTWtQN1EKZSUTA/5vVgOZk2/1Jnh80aWuf12Vkkml
            OMb1bfH8HOD+4Nam7ie4g3HazA1qxcVvcyzwKZ2OU3AYmPA6g6c5kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1grda3zxk9vj9sk06vugpffaa42nw7nmle5cda24ua5udmsp8a90srr4hm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:32:25Z"
    mac: ENC[AES256_GCM,data:U1lsv6ThgJFyMOvuX1l5wB+Mj+Yt3PVLq/UCquyiQXVwoCfTb0gnBUeaaN2udjNk5CJWu/8c9asg12Wz+UITfzjnP21BZuIN8hzfpuY+yCG7VXhsgjwyJRXcgYRZPRxJstPu8+ESubGWU5IgSAlviRDje7PoBb/7BTyRzUuxSJQ=,iv:itrAo0q1NTI8TiFShyGb4NahBWCRzeIiusYuNwtwUq8=,tag:YeKvnIc2hlQU29Y9BcS6cg==,type:str]
    version: 3.13.1
