spring:
  datasource:
    url: jdbc:postgresql://localhost:6433/giano?sslmode=disable
    username: giano_user
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6380
server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiry_minutes: ${JWT_EXPIRY_MINUTES}