// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"user_id"`
	DisplayName          string      `json:"display_name"`
	PhoneNumber          string      `json:"phone_number"`
	AvatarUrl            *string     `json:"avatar_url"`
	Gender               *string     `json:"gender"`
	DateOfBirth          *time.Time  `json:"date_of_birth"`
	NotificationsEnabled pgtype.Bool `json:"notifications_enabled"`
	CreatedAt            time.Time   `json:"created_at"`
	DeletedAt            *time.Time  `json:"deleted_at"`
}
