// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (
    user_id, display_name
) VALUES ($1, $2)
ON CONFLICT (user_id) DO NOTHING
`

type CreateProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile, arg.UserID, arg.DisplayName)
	return err
}
