apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:fk6WKMx9,iv:jKHAgEYB0bk9Cdp4UqP4FNMbYP6Uklnn46zr89m2Wc8=,tag:lLKBUgpCdBBzho/inP31RA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hFqioh87,iv:2bh232N2yojgS9mwRWfasxOxVNynHSJnvkM1Uxr4f7c=,tag:Wx6XoKp1CcTo5ecciMIlkg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:1WXQxmtfNQpNHVOEQ0Bo7Ks8Sf5QFggOw/ucDmJJt14y08c=,iv:Rj9qXdRnXGwGMPDAP6DClMdv00YiAaVzHa812oA9/gk=,tag:7aH4c8j5AH+RwKVylYXXeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMmpZUzVMWkdkR01ZVFE5
            N1N0bG1KV0VrRlpHYm9laXp4ZnhXUjNWRFcwCis3N0VXYnBCbzZ5VFFGZlpZSHNM
            aS95Zm5wRTJzdlJyWFJRWGNwaEdvQzQKLS0tIEdlSUR3aUNTZ1daaCtPbGRUaTFn
            MlVrUkF6UjMxYVRNOUZLM0JQZHB6QUEKUlKIEezk9k8UEvNbv/QwJCSiEamLHnQ5
            9h7DDcAlg5eJZuMnIUHloYMt+P/nhl4oo8y/8s5fjb4hVJCo/Q/dng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:19:17Z"
    mac: ENC[AES256_GCM,data:wVWbvgw8Ua1PEgKeOACE3Z6HLDodWDYlPlnuvnSNU7cYVPJQJcmjkw+BdiVHIl5rfL8/06Fp17z5o9897M+nvbIH8BUE5Tzti50kaFr+MObCUH2+EaEmVWmxKAPor62hzV0B0vExWX+25zaYzl3oQUgkLylXJrs/s6JBOHu9Tbc=,iv:L21wz1/Y5t3nef2sCztFX9DqOzGvW076Toboah5zcWI=,tag:j2ntKdhNI7wbG3cGqTMhNw==,type:str]
    version: 3.13.1
