apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:zf7rmosB,iv:Mlz2svYDwRWxxpg8tA54qXx6tQGuTTPysCgRmneBfqA=,tag:C9kCu9gj6u2O5bs3OMfKyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9iF0yA6W,iv:K6tBj+QG0/zo4f8pPbMWYkgcI7bbhzg/FQitLcBWZuU=,tag:m+ckaTLZCMVZC4c5X++ItA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:0WUn/LNrOqPHIhcAqKI/rpy6VoK5i/BrarnlqG625l5Ske8=,iv:WMJDyNtfqGhF22PjYApzp0rQqLQ3Pr5TT34X8ylE6Rs=,tag:uyxgtvUARWY8my6D4jOmug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdmZhTGtMWWVUSncxVUpl
            eXROQ3F3ZzBoNzdxaWE5NkRCOGhrN1BEelJ3CjRnTkJCMkdiSDBkQU1NcnFBZjI2
            eHFWQk1kdWpWOEtPVndDRmpOdS80WjgKLS0tIGVFYWRCNFFKVkZRbDM4WHI3ekl2
            alVNd2NoZ3VURlovc3RDckZjY2dnZ2cKCG1jJtCBo76FlYcV1aKxXVA4ql/3qVob
            YOJrF55wtetLELcqcVAEOOf+kvBXfcvJFidXzQ1bfvM5UrgV+8kDwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:18Z"
    mac: ENC[AES256_GCM,data:sQhLwcKQQZXauMoILxDnEeuFgxWHbjAwwtQXuHF6hHq7eAxFyqjpLDvsK4B04UrWaXyyxNSOeFi00pX7Y3K5mFGurJrxkekUBGAdUNN1xq/6Wr7yAKs+TCXaP2zk6/QyoXsMMrfJfR61uOzRdBUtPMR3YVNKPGnnbCCDR9dTiv4=,iv:iKLdaD2lWlUMmgnrobbs0xNQK6pd2lYv4mh0DeEo9wI=,tag:P6Z4jk6JiUL8Wfi0UZ8/Sw==,type:str]
    version: 3.13.1
