apiVersion: v1
kind: Secret
metadata:
    name: chat-service-secret
    namespace: zalord-prod
type: Opaque
stringData: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOUd6S01iS3phOHNpSFcy
            WGQ0dXBzblFlQlZtOTFqVmtuVWlmTklkU0R3CnlvOFRHTTFMelpZQlQwbTRTREU2
            YmUrWFhNbStNSkUyVTFybGMxWG5sb2MKLS0tICs5dzNiRFNUTUpuSGJWUVBEZXNV
            eFlzem43SWoxZnNxeEFXYXdVcktMT00KxzPDdrGkNGL73KTIGU9/ZW0U+1CBz5j6
            HtmBO96FXbj/Q12Y1vfz+v3k+lnJBzDFd6473dvluA5+yOsXt8E9pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:19:17Z"
    mac: ENC[AES256_GCM,data:Vutqf37EMzFpMGvT03hXWBG3CJQtaED33mt4v4M4W1O8oa9TXrpFw+py1QdRTobdFazyZO4msjSzeusFd0uGC3QtvRL5y+Q8JOXVNou7UHy/9bT2il4IQMoOc+y2kAWMVAb8OHMys6Y6RG1d9FResLQMsGn6IPOlaz5dVQ/mMaU=,iv:sycBthIQY7kqQDvP3WmW7RbjDGkPhdZNXz/r9kljnfw=,tag:6pSuS/RT57jrqbdZSi9itg==,type:str]
    version: 3.13.1
