apiVersion: v1
kind: Secret
metadata:
    name: chat-service-secret
    namespace: zalord-prod
type: Opaque
stringData: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFckh5TWVzNFY3Ui8vdVN4
            S2VpNjR0WXAzQStaSW1BSzd3MnZlYTZ6RVZvCkdYNUVqWHpPbTI0MExrakdRRTZi
            aVBNdDU2czBjVzVvcGdPZ2hzRjdDZE0KLS0tIHgwcE5aVk9qNDBjWmRCbzhjZWNi
            RFZuNk9tTHlJWnlWeTl2SXdNRXJLdkEKrIqVZHS+mM/Xrrp6mldOHYkDVB517Yae
            BUodF7IXcdUoT8i5xWyciQF/MBD5O3uVdPorabkmAyA8pjn7i2DUcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:18Z"
    mac: ENC[AES256_GCM,data:o5CP0mdjvLYcKYEoLb2t0XepINpjYv9+RcAZc3HgmGsJcQDNtAfCDceXy8q6yMfr0Bys1tfeIruhjl28wGiaKKzf9EwR2T5tGLLlgJ+NYxwhhMQuafNy6rTljCkBpe1MDh/rcSYzgUNgRbZtyBuvImgKA/D53hIwm8BZuvrNgvo=,iv:I+yb/shgnKwWU/AyEmJ2tG9oPnXEBUibff5MCoUGrB0=,tag:eFwuJpYjJpfzEgfD5spHDQ==,type:str]
    version: 3.13.1
