apiVersion: v1
kind: Secret
metadata:
    name: group-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:2O+1tmQI,iv:6loDiIX5x5UgFibp+szXO8znBhIhNeUkIwduXXdFTe4=,tag:DDmbxIBLKM632OihCQtLqQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XAGUD8fK,iv:ABYxNlrwLT674hYMYUUP2RaPprZ4QVp5JGD6IyWBjFI=,tag:kSfZ1IA5OVi7nktyNpv0yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV1Mwak96Q0dTQXdYRkdr
            VnpUZ1ErZVBHVXdxTmkxcjNNWVFTNUtOQ1ZrCjZiK0hlaUNTcWNhK3Brd0djRmg2
            T3lVUG1JVHUrZEE0RFBvaHVsb0ZIaEEKLS0tIFdyQVN1ZVEvQmpSSzNsVnloclVB
            SUdDanN2ajdsUWFiWXAzS1YyQTlJSWMKM1gCwCXaLFFqBx2p1uNUUwzz3tbFtiH0
            oNbOk3wjaFRwugvrDbumOVTIVm0wf2cDzRVHPUMvhIK1wmWbArT9hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:19:17Z"
    mac: ENC[AES256_GCM,data:KKaBHL24/GyNvASbyOkFgvP/z+0Dmi4wND4pQDvh74JTRrgBW+sK3dOC56plYFo8XWL5XBqguBuPrrsGa0VSfa7c/Eyn8XJ2/jJAHOkDujAvx53gdIxMuKMsw7bYRYlKM9poHDMr3gGPXUdzM5N5f2OHBGUpiCT776pMR52BzNc=,iv:5iFgmynHAF33k6ljgYbKEG24csQeKktIg4qFlrOBQhs=,tag:n9qCaz5FXOo7kPnEbXtMbQ==,type:str]
    version: 3.13.1
