apiVersion: v1
kind: Secret
metadata:
    name: group-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:kSeaXxVd,iv:mTB5M+ICk+BI83GZyHtHCAmfVd1OG8RwG1wZ9irbdrQ=,tag:/LBBw6MupsorL/AIP8ywYQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tNTnJuI/,iv:t3NNCQTQvNixBYc4YIneZh3XRZfCqL1+rbaMTcitBaM=,tag:+3GhEn6gy+Zqw+AVysdi6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcVo3dzljYkRKVUZUblc2
            YkhqZjE1UFJWOGJCNGdONHphQ2x1NFZoOGpzCjJ0YVVvUG5ZZlU3VUxlOVUxcElN
            THVvRjNCek00VlovZGVsVE5EMGpwL0UKLS0tIHFpMnBDY1VqRytQWjExZDBtRGY4
            SVovR2JrZUl0R2RxRlpaYXB1R0tPMWcKcxM1vSl0fMRH5EYSPn+6Vxr59avrYWMm
            AaTwj0/EG+jigayc9iIgLC5m0oROQsOvHouMK6GV525afzteZPYdkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:18Z"
    mac: ENC[AES256_GCM,data:fPVT856I9Jrh+uq1dzaAMsoUNQb6fcN+2H8dVevVNdjulLuiV3tZX4naEkt7oNl+gtA0jqjrKIkeM8uUbvxzqgLXJWAgs/yjU4g9FTmqmrLK5jP6glrDpm7ylpk9Ww/YvVmQlqPMQdb75PzshK/5ksfDPcA9iabAHrhGeS/YkpM=,iv:EuoY0NY11sAFczcskoO6QH7UI6XhxHSGvTYiVv1Pn5s=,tag:32xKXblakPZG4l9caN/ikA==,type:str]
    version: 3.13.1
