# Development placeholder values. Replace before using outside dev.
apiVersion: v1
kind: Secret
metadata:
    name: media-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:1UY7610E,iv:NxPtkk67/HMPotPKC4mHNgBTNq/6g22kw5VwJ8j6EjI=,tag:YF3cK9cxgBs5BF8TkxIQKA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fyQi38Ji,iv:Nde3gL7bT2ytmk1sCMmr4CRyyVRIb5qPuXzfnfWM97Y=,tag:5+QR4fLVP2OK6NXev7Yobg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:1wGUgB0cX6WE+Q==,iv:ESjygssOj42oEvWPcH41cKAbd7gdOQif5cmvV0jucFA=,tag:Nte1SfDbXLTrljCbWxJlGw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:0ETkqc3/6rNV6L92ruWn,iv:hf1heRtDiiqYNN+Jux7KL+0TFofDFpD2kWmW3akEpS8=,tag:aqF8PxUP10OJvT08E8vdnw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaFJQM09nTy9Pekl6SGdr
            WVNFSTA5eit1YTJxU2pZWExyd2VhcG5jb2cwCk04bDVlSGtPT1B2MEtsQm0wYTRP
            TEc4RHhOQVdmcGhnWFFQVU4wWmlRVFEKLS0tIDJ3dEFsRmcwQXZidjg2M1BvZjhN
            OFJBZnIreG1zSVZhU2ZuTE5xdzJBeW8KfhjePl189eRmjXte2KK1tj5ZautuPJLb
            QSP8pp+QxSTR4+wwvTW+vPYl2DnyZHDMn7Cl5alRxbPd6CFLr+lMvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:18Z"
    mac: ENC[AES256_GCM,data:ia53b1TpQszU9ykwbFhYXwq0iGFU8VPCSCB/6hXISc33h1eS44El+YYB0KU73s4U9flEamMevTWLJdYVK//rTmAyRYFwoXVV8TnenN4IeqixG8e12+TNRGS3IVR6IwDuRvTw/Fx0CZwzk63r5eq/xnX4huFKlaLAS/e9pqzKWhk=,iv:TZAB05UcYsWaj7hES1QYM/9VT2g8xZ6cwlt0q1PBRQo=,tag:AfFN9xg6Ug509T1EYJkJlw==,type:str]
    version: 3.13.1
