apiVersion: v1
kind: Secret
metadata:
    name: message-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:CM0nVTFt,iv:nua2Bx/BqMLDizxIVynBEXaGHVN62EBvaW0theqAaCg=,tag:Vn3LKRs+6UTPSTsCMw2gxw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:uUc6tb7I,iv:Y8DaaMYLOlWIKwMKgZG2/2hfZbXDJd3TZYAMxmd1BRU=,tag:8RgK+hIJnzP5JNmrUvdhow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VUlpUzRVbUJjVFZJcTdH
            V2VvNmVoUlp2aThaenBqdlMyQkNIOHpPbjFnCmVmZFpGSHRRYTdieHhHUEJPTWtu
            aWh6NUgydnEwZVhrNmJZVzJSMW15dkUKLS0tIGFpS3VGYnhzdUltMVZQNWhFWk1v
            MTE2bFB2M3VXcFl1UzRENll2SHRpU2MK8x83y9+nNN65RhIQFaaDZB4Aa97N3Dgm
            mQQ01JcX0SUoVxNhsbAe5Fki03isnVJmbR9f6EjWoXMAop42G+AWrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:18Z"
    mac: ENC[AES256_GCM,data:/w7NQlM+Kn7jnVjk1fU5d+caOBono8aNE+9TFkWHKbYoAZjciODkrqRFNR6ZK00TvUDWS3NkF+q43lQlsFu/ZusZMvtw6uBA0RWJuucqvxxFSU6j5r9eMc1z2oi6vXFiLXm4XfA2XVVYZWAjsiV2Kc7xIJGB/aRd8G6ldODYAeE=,iv:ABVmFtEbD0ovZbh7OE+1NV0b5PPXf1cAoylXaudSafA=,tag:fOAObEsBEQaAlNZiQp6wsw==,type:str]
    version: 3.13.1
