apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: zalord-prod
data:
  POSTGRES_HOST: message-pg
  POSTGRES_PORT: "5432"
  SERVER_PORT: "8083"
  ZALORD_MEDIA_SERVICE_GRPC_TARGET: media-service:9086
