apiVersion: v1
kind: Secret
metadata:
    name: message-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:dgxw6Mvv,iv:hbGlpb4z6EKKWGEGqzTh9+LdoJJ0yYD3liFyo71aYNA=,tag:ytk2k9Ip4Me6RdfiW46ROQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:d7HmWmLx,iv:ZDYivkmwHTw++6ok7khePhvSDigpJGfSvwcgcKwyeHQ=,tag:Y/DsbMGM3vAR8jP/16mSRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVVpvbERhUHE2MTRQTUxj
            Zjg1bk1ubWlsZDR4RWhXa1hxdGpQVER0VlhnCjY0VTF5N1FGK3FDeG0xaXpFZ05u
            Z0JNUzBBcGxZVUU4MVZ5eGxTblJ1RkUKLS0tIEc3WGM1clhwdElCTlR0eGhGU2Ni
            K1QvUUJ1S2FWNkozbGdTM2ZPUmttS0kKcSMWrdXqyPRV3HDxgLGc9D3dKOIMvy9N
            aqriNzd98dGk4NHYLIWxtbPN3sLMkLq4pGCtoCEhdNbgWPYr4ynKuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:19:17Z"
    mac: ENC[AES256_GCM,data:43iJ/Yr3Uk+QFlBgAZ5z+2WgomroiKcfoEdaTAilrG2HMEauiQBBojTAbk0BTaFzPkGi8XK/nkn6frsJnpV2VVvOSqstnR8C84PC2kedScTatNVRgTeQC8FboQq6OiwlpOsKMcZDWqnGsTs9SdvpSCy8VrvMu6jIWSp0eN1ciYo=,iv:1UiTLyvwJj0ITtsjiE+e1+68FNT4/GcUt1b3bArZeII=,tag:TUd+VJZhl0q2El1DR+eCCw==,type:str]
    version: 3.13.1
