apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:WLZCcZwe,iv:m1Hd/CB/CMxQ6Z1Y3tEDzadaQAQHqI17UMXM1OpiMT8=,tag:nbzNbrPujyC7yzmImgEmKA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:K0fJwiu+,iv:T0MX831EFi6dS83TL9YLr2so6FlNZi2PE0XQpOIdqXQ=,tag:3qmPa0UaTgB+WlIv/me+8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbVVxNDFxQStsWFZqNHh2
            U1J3cnF3SkFLNjZPOGVDU2ZYOURxMGVzeUhJCkpQMG9wZ1pmZmQ3K1JrbURWL0x4
            NVh1Qnh2dy8xN09weStxTU1xN0pRTXMKLS0tIGlDVXNkRmc4MDNrWDFyeUg2a2dU
            czVVamhKbUtZaU1yaVMyMWpLN1djK3MKQeg3GSU6p/kvW+ZxUPPehd8Jxt/xGr6n
            rLG6UlcvGZa51reLUQ/Mr3+4zr7VSM9yXqGrbJydSh3GBgGDIQQ5Bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:19:17Z"
    mac: ENC[AES256_GCM,data:0Hb35G0P+Y9PQ4Tr1Gmg9SA75DjJ/FS90f2ICTkeI2G0splohbEmv5qGuxEknP0X4OrTseBhfzU8/mUJVu2zwfs/LjO8W1y6s0VrcclBTvUsfLb7iCXDzIETaj3PQ2/UrDQFUgCjoMvwQewqKzyB/LgVi2RsXlOUNU9ApOScE5Y=,iv:QOhC6lMkQkut04IlUYsZhOVjplHmgMKHlb5HZik1MXE=,tag:P9Rn4NiGSNtEKeEGawrlbg==,type:str]
    version: 3.13.1
