apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:hcqCDD2I,iv:OnotYsdVjDQ+Cxk+zWkZkMcsQCcYOAl96K0LZsJwtFE=,tag:qcidisSZj517CmoOegfzSw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gydv2n0e,iv:5J9+p9AHzGNVLXLdSAXAuyLOcKhN6Tmh3whi5EaDGKE=,tag:4x+S7KHrOq8TcLB8Hov4tA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ2pwUzdmdkpmdzRNdEh6
            MWFyNlJoakxFb1RzUzZETkhwcVQzalp5L0FFCk1veG50MnB2N3ZXTlNzNW9VNmFK
            aWxpbTNFK0FQWkV5Q2t2amdZWWVBbG8KLS0tIHJiSSthN0RXbWpoNm8rcHlteFZr
            N21MNUN2b1c2b29tWXhlSXQ3OHpWVzAKQzE+JrI+QkrehQUTLWB9NDsRLcwxzjYL
            nzGBOMsRwSeabb9XtP6M3yMmRfWOjuFmHizHHnqSGI2xGQSST95nsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:18Z"
    mac: ENC[AES256_GCM,data:SFl7DSfIWyOlYGqWufwfZx/fP+hvchnXm+gpS0/jvi/9/IQPqTzHL7UJqrUDpV+lvtcDYQBZB3fzsypfPURArh3cWXdqcyEgkKiQ99cHdn8Ab3xMg/DM0n9+HEiSATEQ/qvG8HnaX1aWC6iVMcGB42usgWhULvzJqlJ6qlLIzzw=,iv:aE4izaEOCDdc8ktszFGu1iJyPXWDHsvk0WjMtGiKkv0=,tag:wDC2kRQvVmNtt3qynKgAOQ==,type:str]
    version: 3.13.1
