apiVersion: v1
kind: Secret
metadata:
    name: shared-secret
    namespace: zalord-prod
type: Opaque
stringData:
    RABBITMQ_USER: ENC[AES256_GCM,data:ZV/IJ4s=,iv:NV1Y/uml9QPjZtBMxLhdz0XSll4NtviTYpGsHLEe2QA=,tag:J+m3BcPg+0twV4ESXNMerw==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:qPliSrc=,iv:DPQmF72P2273i5+4kV7V0MJFgGkFIbfYYS9LKLJTCVw=,tag:A/vNJNgX3ehl+zliTgi7vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cnNQVUhnZTRSNjFmdTJv
            WG82cW0zUldOTjlOc0Z4bGU5aHVkTnZIMmpNCkVDYzRPZnRleHZIQzczbW81ajVk
            cXBpbkdhMlIwOGowWFd3aFVLa2RyMkUKLS0tIFFSanRoY1EzR1F1aXVERVBvVExl
            OFZ3cnhYNTBrR3NTVHEwN0g1MlJEc0UK7VxdK+v47b70k9CZKL6+qlOAmTvIeAt4
            jyaQ9pa2VgSyGJpYOYGpxtUsW10EhZxK+n9JuL4QFXgX5vQArZhOXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T16:43:03Z"
    mac: ENC[AES256_GCM,data:yGwOM7odUvvQj9B/gLeDWXxMUYwx/2oQcwHr1A4QJuqzlqfnOT3HVaQbBCwDDUJwe8PcFmlg4WUxGGxVwlk9PsoHNzpJ1GzWg8crXxFZB5Rd66an9cQVPUtDYGP+S45yGRSPzdud/tERNLlBfD3a9BfEUQuccVwjz0AM+N9t/M4=,iv:7TAEFySwwwtKOKEem1AQKM0gTZ4Xf3b/zRFmgt0LVjw=,tag:kekWVDhWGzRNgxZnbc484w==,type:str]
    version: 3.13.1
