apiVersion: v1
kind: Secret
metadata:
    name: shared-secret
    namespace: zalord-prod
type: Opaque
stringData:
    RABBITMQ_USER: ENC[AES256_GCM,data:bfDqopU=,iv:M5erdA9KgmlXfm0JB4pFUlyAkR5cEaYIZwZy2QbseKw=,tag:kbcxpcFg/AOvztcYcbg6nA==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:Q53JB70=,iv:LH38grM0634dHojI2i/DtoFZmSJeaE2tH/2Q1fwJQ4c=,tag:aO6t/61bGg1Qlm74MEX9mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZGRUT2JUR2VRYXp2UzV5
            cWJ1b0ozUHQvVnpULzd6Z0hDdlliclMrUFF3CksyTU82bUk2RWdwYVRkdFg4aEZJ
            UDlsZyt2anFjK2xqU2J4b0NmdnUvZXcKLS0tIFRtVmxjc2gxTEUybU4yQTB1Tnly
            dndmdVUzYmgrMWh4UU5nZERneE03SHcKwFd7VSAv/loHkF1TKtmi4F4/DgwQS9Zz
            pa16NBJnVva5AI5mAZab1+wwvTCkcgaT/kAEZKqHKEyk6tfmg7BlVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:19Z"
    mac: ENC[AES256_GCM,data:/cxitnS7pGNrRGrVSW4xMlwoeSevsy3CnJZLq0jFkxl7rRCAgUnilp/8d3t5ir60ZjDbZ02xv6bsgTL+PaJBKLpIXEpbzSq+WrotPDIh8Hkkg8kGt2M5zeJ1lgyAZn7HP6jbttHWfcDEXmi4L1/sklwRj0W2vSIeJ7flvyfZ1vg=,iv:JMG4s3jhO3G6kfA94tGjiScarJjcymdLKjz1Rt/+nBM=,tag:lio8zeu1KYtyOu8sU814qQ==,type:str]
    version: 3.13.1
