apiVersion: v1
kind: Secret
metadata:
    name: user-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:YwyCZ+ld,iv:sco4pBILmRQ+j4ikxO0vyQuDVr53IHMrnPQTrcUgEoc=,tag:jDfI17ZsS2Ph473q8IvC8Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3H3fYDqK,iv:OTvk/mOyOAlkTW+WfzDHCrdQlDSImEcHbsnLU9pi/VY=,tag:KlYEED0Z0T/eRRKrXnkfsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ0VKUUl2dERNdGZoYm04
            Y2ZEeHVoWjZnRmpmUTFNbGZGZjZCaXdERGxvCkRTWjR3TkZxL1ZrdHhlL3p1RFNt
            M0lraElLLzNnSUhSczc0Nm0zQkg2MEkKLS0tIGVMbThuclpQVDFNcXdIYWdxOUxC
            bVpmaDJlcDhKb0pTOEV0VklYc0FxaDQK/ULqWgZ7U3ti0KgDScjB8tSDP4dyIeUW
            8arpKxynrJkYff4qpHm6rLBxRiqqM30/FPyBrABJlc0jNrN7WrZV6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ejm0l5e55vsf6g4r2zg2kwfdczyree4j4hj4uqt2eptxwnwfgssx4qmk3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:03:19Z"
    mac: ENC[AES256_GCM,data:K1sie/DnIz7l0df8vumJetEzEaoejLNB19PTS5N7+6gGNMeV7FpQWVvUji1xCA09eK0RVYvT/U83G8gXqwnsvu+e9y6BdBVOiGBvb8h7zJFB5AVg9re5yvGWevD1ugaQh18l1ZrpMRdxRMetbChVdYY6KEUD2F+ogYy0Di9YT5U=,iv:B98c59E5Q5wWFzyl4L1soaU2gHzUMukFWKlXBC/fy2Q=,tag:nYt7Ch8lNuJsT9RRvWn17Q==,type:str]
    version: 3.13.1
