apiVersion: v1
kind: Secret
metadata:
    name: user-service-secret
    namespace: zalord-prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:DTXNTnyb,iv:c2kXZYqE8m8MCZWjIh9UgYLkyr2Fwo2OEIcD/QySB9E=,tag:Jz6y5JVDxCX+XZraELDnZg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:n0g/bnct,iv:Q925XJ/2vKyQe6ptvPcrm2U/w9MhbvbTTYdMEcwKO8k=,tag:F4Gvu9w87AY4OJZ2GjvypQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMHJrd2d5WjJmajFIR21V
            KzFvQlhOSmY3ZmtVaE9wOVR4bnJnSEh3Q3d3CnpSZE1sZXlrOVR4KzU5WVR1c0pD
            SnhHanowT290elNINk1ZWEsrbC9tQncKLS0tIGhhMlRWemVudjJYcXlXaUh3amRY
            eGFya2VuNnRISThqQkpvTkpXUlJRVmcKNqKdPl2iiYA7a97znRcRSlSgE15uHrcr
            1xvwhTX+gFq8P091yNvnVL6hai7t7OfkVYopefPkPDhWg0292Ss/xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T17:19:17Z"
    mac: ENC[AES256_GCM,data:+OSUsg5B3h1p+dBZ/9hIPZVz+11Y68ZdzEbKyxOKiNUJ5pq7vA/a1W/kc4QZSS8kpRZNtW8q3nLGPS8r1sryeValSJpYgOEyjZpRvHi9mqCbpyqO3qXtv+1Mj4rXQfFNsWm/3HBKOUmIEi60uIJsAbJi4progHSvh26d7Q3AvUU=,iv:5VwK3BFqr57gEQu5or0sNoKzxuOHN+4+aBV45WCgBxA=,tag:iUPmKgS4LbHi8/Xu9PDUPQ==,type:str]
    version: 3.13.1
