#ENC[AES256_GCM,data:TYzapj303qimui0NHdC9IjsKQZJg6P9IZB8IljgH3aDALw9UL41MjT0GtgGABvJGWWrxdgh1o5+JIJFEmuy9VKMB,iv:jqE8yy/p5xy1ZyYKqettShiusZzh6UqVidAtzj1NOpc=,tag:tUA0k7QLA4xaPnujRsurgA==,type:comment]
apiVersion: ENC[AES256_GCM,data:dC0=,iv:GwYhcmXK/pBtqDtUyQkWbwxhvaeHEfY3YZqDxASVLHE=,tag:8O1qElI/YRyY59iuyq6tIw==,type:str]
kind: ENC[AES256_GCM,data:K5aQ0WCn,iv:6Sp/haoeWz94AdW0Qu/TI6gl1H9OhdvfkqkIhi8MxXE=,tag:9SxUL+SK6r+uTIO0i9s0+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mw8rnInONTlBwUg8650SxgdgMA==,iv:actD2a+p2QqsL2dNYj4yqZXYToLRpf6uU5g9368LHGc=,tag:iVS4x5mUJ0TMyOCRlhSMkQ==,type:str]
    namespace: ENC[AES256_GCM,data:EW47l5H5WCLR+g==,iv:QODfMnhmqg+gK7Qz0NqPS4k2ZKnZxvemQk/N+Mz/btE=,tag:NVmhp7CgMrOx6WJ9siUhLg==,type:str]
type: ENC[AES256_GCM,data:bA7Jz/G4,iv:sRTkAWzGRjHerJoJj1YLtsj3Dtm1JzDeHFvkB2MPueQ=,tag:7ProcdZERb7ne9A6OkPvSg==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:AUv+n4QZ,iv:XDO7tdUOPbwIwfIOAjxPYeMWGIt9CUSpyt8aTGx0goQ=,tag:uSTJynmlEkhPHd9WvT/t+w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Dn3Pm312,iv:61zvGwMGpk1WqC2BXRLSIrKyTzO8qoda2bYuEUEvrTI=,tag:qCIaoubaX8EgZ/8WWt9TRg==,type:str]
    RABBITMQ_USER: ENC[AES256_GCM,data:2OHq+jA=,iv:G5wgz5amuyUzcKw5sWW9t7c4lEF8xWCJXVCfDZic508=,tag:PhzjHom/m9CcX/yIOMuGBg==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:we8jCI8=,iv:wxTLWRu7VIAlmuS0berJrqvqghdr6clv8liinNk+b5c=,tag:jw094D7wfrULCJUaXXbxlg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:8o7vSyje37nWvd8W1XWU9Qu49GdsYdsf9Lwj269AM6CUPog=,iv:pXnSTysiStH3VvVmZ1iJhMbi9veH3F13OR+/XEjsLR4=,tag:Y41mZHW9C8IFnIJu7rn60w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ2w1TlFFaVI2dU1ldXox
            VXV4TTU5UFMraFdJOGY4Q05MTmtZVUpjbEdFClR5M21YT3AwYnE2dVlVdWM2SXVw
            V2JESXJML1BKRUJRbjRoSGpBZmpHWmcKLS0tIEFwSVpsaFlwYTRWbTV4OGlpUEdt
            b2lzTEpOSWZTUUZwck1Oem1zWnlsVGcKTKPpEzk94DbrYKLdQcVwchklz/oQ3zxf
            zml4w+9zys3I9GgOVeGzXsBpsC4Wh3fb672+rDztAcYP8N4TEEHwFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    lastmodified: "2026-06-25T11:10:33Z"
    mac: ENC[AES256_GCM,data:UAqHCB3VrmudmP95yDMD3yaXB7uQYf26sOvYoENRqBgHlTEe7c/UqdxeW24ojLML+YTB53zO3ECXTKTVftKv12DO6GFLSatt54JzIoMWLb4RfVRJ/D/nijZ2/vyL8imd9H0G6tllCWf4ywD8eCvSZuqTfNDFjXkwN3mmdFjJXUg=,iv:H/WZW2aXcknTKJvVJsh97344kM3EHlnG+lHfE4nLa/w=,tag:lE388PlNU0rhD72jeNZMrw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
