#ENC[AES256_GCM,data:lHzzjlpVXOF9GIMfMmbhVvMUQ1I74iB7qD6XysrRibH4VbINCs5ZNHjtO0t5nYfp++ReLLECUBoEa7aMTHVG1k/W,iv:nLlfC7EF0xDV5kjQTBzms1v1BvupCKLTzeH0hv4jLz8=,tag:blve+r533biEP9mG/mKfbg==,type:comment]
apiVersion: ENC[AES256_GCM,data:chs=,iv:SxPyp2ErXz72qNDSxD4buD+F7N4OgRQVjm4ekQsuZvo=,tag:g3+ZnfcHS19MuDETb/FLtw==,type:str]
kind: ENC[AES256_GCM,data:uVew0Xbe,iv:0gQt/NHG+l4FAj54yYGm5bL6gHiFBVuphpPE7lkOq5E=,tag:gUIi2uPrbCOe5Q2uKBTl6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gxTGkKBC9AI3DcV5XdTCmC1zwBM=,iv:/RSXvN40Uce8cJ2LNS6bTQYjQ27tPa32UyQEfZH15EA=,tag:RHb5vZiKYwSZWqHPaNr5/g==,type:str]
    namespace: ENC[AES256_GCM,data:ClZf+EmwKOCy5A==,iv:YZ22Dim+bIeP76bTDqzx3PQ2zsztf3TbkALLlzPk1Cw=,tag:W6GDv01lCtPfTS7Zlz+u6A==,type:str]
type: ENC[AES256_GCM,data:lm6NgrUU,iv:CPi/LNo1ZYC+jLdmZHUMi1TrzpVuHK0bc1oZS0nM9bg=,tag:lRMV4F7MPcHxblOdwjybqA==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KU4Qnv2c,iv:uUZgBw7aVpQTcFhZAXaNOM3y288PnC0Cj3O++tGhFEw=,tag:fbOUWes0xHMgEspJrBl4hQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:1Tl3rrmC,iv:qVRcfL+sI78ek6D8qs7gw/yRMB31RP6B+CH0D9glBv8=,tag:HeVtRFf0ERIQs8xY/hPxFg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:aPyp+cE5+GBE3w==,iv:jHvjv/nKcM4CPjTbCkBVIe048cQVCupf5D8j+iFTkZE=,tag:GlwQ+UZeOakopHo7yuTiNQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:WNTIWbBM6aMhIShpqPLH,iv:dq57zs7ov40Ba0/20xT0sd0TPEoXgf+RWX+r4EbYwMY=,tag:Rv/QygE/5rfJoqunvRxoMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWFRyVU1EWTRTa2NYV0No
            dlErTU9pOXM4YTZvOTJUSmF0U3BERWNrSEQ4CjRxd3JOZzNsZzZ5VTlJd3FOb3pr
            RUM1T3VSbFlmR1JQUFVuUU9SNkMzc3MKLS0tIDdnSkV5dnJZb1hCczBIeWE5VXVs
            dkUvMTVJRzVIMlYxT1hFWi9qa3ZDTDgKSnf7U+wsfx+Kl7o3AaRHHZ3oIqB4xjYh
            k/BOthILjYgD+Xml4/hB+P6ophgix/7/ZFwaoMGBLn7ylgQrMb32GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    lastmodified: "2026-06-25T11:10:33Z"
    mac: ENC[AES256_GCM,data:eJSlaWEQXey4wlDY9Az/xtysQXvIQTPnHn75K+YP9YjEcRFK2P51eEsy1TZXWgoYvsCi/XWLt0G6h+M0TJD2JKd8MSbNcoZ+en6teOLpJHl7Uf57DNZA4yQWHI1kX0pOc9ult1Fm/alwwnFPHIxtLrkKkxvUJjBXY5bOmzxRXJE=,iv:4BqLqeDPXOEhTs0b2ffyQp0aV1xUAi4V1HaqOft4RVU=,tag:dA/x54mTFJQD8/sbYjKdpQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
