apiVersion: v1
data:
  MINIO_BUCKET_ATTACHMENTS: attachments
  MINIO_BUCKET_AVATARS: avatars
  MINIO_INTERNAL_ENDPOINT: http://minio:19000
  MINIO_PUBLIC_ENDPOINT: http://localhost:19000
  OTEL_SERVICE_NAME: media-service
  POSTGRES_DB: media-db
  POSTGRES_HOST: media-pg
  POSTGRES_PORT: "5432"
  SERVER_PORT: "8086"
  ZALORD_GRPC_PORT: "9086"
kind: ConfigMap
metadata:
  name: media-service-config
  namespace: zalord-dev
