# Development placeholder values. Replace before using outside dev.
apiVersion: v1
kind: Secret
metadata:
    name: media-service-secret
    namespace: zalord-dev
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Xjc8YRY1,iv:PKclDJMEY7Yz547cMVEFBxuMHgVssED5wdMJ9nyaL3A=,tag:+Xdx4ZTvYcdTQCYmlg5NjA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:50mK8NPF,iv:meOyzb6prBEOocFTi6AgruTKclrLcLlpmgHaf0/FCi8=,tag:2DHTCoMPKCad5ogEoEaGeQ==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Vh3Ydgzxg3uepQ==,iv:YSdz1NCwmzlCDlgdeoDu48X+ViemzKxq/t3qtAyvSIw=,tag:Hb3pDRkHNk+BLw0ncDGLPA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:a/cBO5sMqNbUgXRFxThQ,iv:vsJtBDzLOUZdRAh4eGEl/G54dJekY6HZNONRptKa24w=,tag:5bveM5NA4XYBfJ6N+quo/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaGtSSGNCWFhTbzBPSW1l
            UEI2WHBjOW9WaUFEQnhIMVhQZGdjczFaREVRClkwVVd6eFVlem1FVWhMb2UzRGhn
            UVY1Q2oxbkJ0ZXRwTkhzclhQYS82c3cKLS0tIE1zQjFCWllhcFBTQ093V0RneGJN
            b0xIQlljM0sxM1NkZys1YktOaWtuakkKZhUIEawGOjkMP9h6JVAFEYghRrMb29ZK
            KUv8Wrq5w0IMq/PAOaGLAHn9KrVrpmR6hrw/NJW/RRBt0X/b3D+pnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-25T16:42:44Z"
    mac: ENC[AES256_GCM,data:zTsUIEI/DouFPG/mhhlAkwTrP55waW4HBuaAUqT0UOs2aqLyHrlzV4wv1G9WudW3ezBh2P6Ag/lZt4dXW1HfNTeLNaVHfkMCvGoqEtgsAP+qCc+QlL8DHWGKkLOd75YA/DdDq3NVd+TJMskPpxeubzTdLuMAJ84dc8AC9PJK5tc=,iv:GKZ4Q2TuSOVK+9EqExl5BlQhW6kpZ7cmn4GLY3VRiq8=,tag:0j24J8wCApQSILaKNHAAjw==,type:str]
    version: 3.13.1
