#ENC[AES256_GCM,data:G/PUDfMryZPKGQgNdlaW9/vcjQMIQTnCKnjCr2RPH/dT6oeeCQQFZ4cuzPy8LxVVwCevzwdwYPUSPWl62l0TKLny,iv:PwAt9cofBPerCetCPtUMP2IO3uciHDQ+UtWKcyudhdk=,tag:gRs1dVYv8zWb0WfQYsN0yw==,type:comment]
apiVersion: ENC[AES256_GCM,data:jMw=,iv:cSBP/xwkoOaTq5axCyvHaKdzRiJr50j/PLHeRdWq9A4=,tag:E4V248IEaABryqezLGy/EQ==,type:str]
kind: ENC[AES256_GCM,data:rJ3FuBxv,iv:HVIzygGRNSex4O0kyrSL+uZD0ew2LD9/8VQrxRRYyLY=,tag:Jn6Uozemt2r1ScuSmr3OHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KaE9yNiZ+ctoaN4oVVMh0yPEMA==,iv:Tlq/X0G61ysj9mxfazzgskTD7X3icsx6we6oMJrz/Nk=,tag:xuw+Efh2irQOKvwTo05fjQ==,type:str]
    namespace: ENC[AES256_GCM,data:lz3NX5mTk7CSYw==,iv:rdeMnH7L2VfI7cEeHjuEcbB/2DJm6mIZYJAqw9xA904=,tag:UjmY8+o8kGztw2fEvtc8nw==,type:str]
type: ENC[AES256_GCM,data:JJ+qo6zR,iv:Va36e1R8DJqD3eNEXph4uTCguGEKrqRsvVNmUhLTj1w=,tag:UmKIZdStVVdQ/TnJKfKoDQ==,type:str]
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Ao3nvVjl,iv:nAt/S46vrTHx+C2yrp0fxMhQTRBwi//OwqzOQ7yVaO4=,tag:X14m4s2nSrMMhDYe22jftA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8suKB6gI,iv:iy1HNVVnRKq4k05YK+iE451v69QImmDHZf4sVn1Akag=,tag:BrPTHi2CbH7gsY9t0hWQpA==,type:str]
    RABBITMQ_USER: ENC[AES256_GCM,data:Id2wl94=,iv:k78oagkaooIzFrbEAj8XKeK0WL3LqrWgVKb9axagaLM=,tag:fcVCISLry4OEk+9lyVAc7Q==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:6UVS7Xs=,iv:eL+eGmb4IitPr6RM/msBB/DoGv1uIxGZdkFGd+lfnyM=,tag:l/etCU4qvxeR1fubSV+EJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVzUrcTU2MERPVEZBYlY3
            RXpqY0dBM25yRjhGeVFyYWhtc1pTWEl2RGo0CmxDOWUwdmZBcnhTTkxrWlpZdksv
            SDE3U0FvQ3Uyc1doRFFRMkplUFpoVGMKLS0tIHFGSDVLNjhad3QzdWlBNTRCalNW
            S0tqTUc3SG9WOUExWWR3UHNVNFhnNXcK6zRMTjslpeFBYIH7pbHJk/ePO1UD7jJB
            lPndPicRsOOqMFSfdHHX1WTBST5BiXeTGGXsPDUr0jhlgau/ZHD0Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gsw3rsazcn7x6mt70xuw4xedffaxdukadl4xw6ll5vz0qe8ep3gs6he35k
    lastmodified: "2026-06-25T11:10:33Z"
    mac: ENC[AES256_GCM,data:nzHUE8EtvxZ7L27eXkfioPP8Jh2KeKcIY25iXG/fs1hguP7r/cSje9St1S0hpdLBf2cEoLaB+UOfbtw1vNn6LcinVHpZ+aH+e/U7wiV8nP/DNxRI/tb8QloWHShor+pUbgemUOlO/qyjQoEobmmd7tJ3eiUElpInnU8iRuGeT44=,iv:mC92hN88dkryg7JA0KJyZeGTP4vwnWU0L700/qneLkQ=,tag:duh8heI3LTLQcF6GcMT9vA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
