apiVersion: v1
data:
  DB_HOST: user-pg
  DB_NAME: user-db
  DB_PORT: "5432"
  GRPC_PORT: "9082"
  MQ_HOST: rabbitmq
  MQ_PORT: "5672"
  OTEL_SERVICE_NAME: user-service
  SERVER_PORT: "8082"
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: zalord-dev
